"""Verify paper template, claim map, generated artifacts, and writing boundaries."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from scripts.verify_evidence import REQUIRED_CLAIMS, SHA256_PATTERN, validate_evidence
from verify_agent_memory.provenance import sha256_file

RETIRED_LABELS = ("ncr_threshold", "ncr_a5", "A1-", "E1-debug", "E2 ", "E3 ", "E4 ")
REQUIRED_GENERATED_INPUTS = (
    "generated/paper_numbers.tex",
    "generated/main_results.tex",
    "generated/full_arm_results.tex",
    "generated/matched_prefix_diagnostics.tex",
    "generated/mechanism_smoke.tex",
    "generated/verification_pipeline.pdf",
    "generated/evidence_summary.pdf",
    "generated/retrieval_results.pdf",
)


def _safe_path(repository_root: Path, relative_name: object, errors: list[str]) -> Path | None:
    if not isinstance(relative_name, str) or not relative_name:
        errors.append("paper artifact path must be a nonempty string")
        return None
    root = repository_root.resolve()
    path = (root / relative_name).resolve()
    if not path.is_relative_to(root):
        errors.append(f"paper artifact path escapes repository: {relative_name}")
        return None
    return path


def validate_paper(repository_root: Path) -> list[str]:
    errors = validate_evidence(repository_root)
    paper_root = repository_root / "paper"
    main_path = paper_root / "main.tex"
    checklist_path = paper_root / "checklist.tex"
    claim_map_path = paper_root / "CLAIM_MAP.md"
    manifest_path = paper_root / "generated" / "artifact_manifest.json"
    required_files = (main_path, checklist_path, claim_map_path, manifest_path)
    for path in required_files:
        if not path.is_file():
            errors.append(f"missing paper file: {path.relative_to(repository_root)}")
    if errors:
        return errors

    main = main_path.read_text(encoding="utf-8")
    checklist = checklist_path.read_text(encoding="utf-8")
    claim_map = claim_map_path.read_text(encoding="utf-8")
    if r"\usepackage[dblblindworkshop]{neurips_2026}" not in main:
        errors.append("paper must use the NeurIPS double-blind workshop mode")
    if r"\workshoptitle{Who Verifies the Agents? Toward Reliable Agent Development}" not in main:
        errors.append("paper has the wrong workshop title")
    for generated in REQUIRED_GENERATED_INPUTS:
        if generated not in main:
            errors.append(f"paper does not include {generated}")
    if r"\input{checklist.tex}" not in main:
        errors.append("paper does not include the NeurIPS checklist")
    if r"\answerTODO" in checklist or r"\justificationTODO" in checklist:
        errors.append("paper checklist still contains TODO answers")
    for claim_id in sorted(REQUIRED_CLAIMS):
        if not re.search(rf"\b{re.escape(claim_id)}\b", claim_map):
            errors.append(f"paper claim map does not include {claim_id}")
    for label in RETIRED_LABELS:
        if label.lower() in main.lower():
            errors.append(f"paper main text uses retired internal label: {label}")

    try:
        manifest: Any = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        errors.append(f"paper artifact manifest is invalid JSON: {exc}")
        return errors
    if not isinstance(manifest, Mapping) or manifest.get("schema_version") != 1:
        errors.append("paper artifact manifest has unsupported schema")
        return errors
    builder_path = _safe_path(repository_root, manifest.get("builder"), errors)
    builder_hash = manifest.get("builder_sha256")
    if not isinstance(builder_hash, str) or not SHA256_PATTERN.fullmatch(builder_hash):
        errors.append("paper artifact manifest has invalid builder hash")
    elif builder_path is None or not builder_path.is_file():
        errors.append("paper artifact builder is missing")
    elif sha256_file(builder_path) != builder_hash:
        errors.append("paper artifacts were not generated by the current builder")

    for group in ("inputs", "outputs"):
        entries = manifest.get(group)
        if not isinstance(entries, list) or not entries:
            errors.append(f"paper artifact manifest has no {group}")
            continue
        for entry in entries:
            if not isinstance(entry, Mapping):
                errors.append(f"paper artifact manifest has malformed {group}")
                continue
            path = _safe_path(repository_root, entry.get("path"), errors)
            digest = entry.get("sha256")
            if not isinstance(digest, str) or not SHA256_PATTERN.fullmatch(digest):
                errors.append(f"paper artifact manifest has invalid {group} hash")
            elif path is None or not path.is_file():
                errors.append(f"paper artifact is missing: {entry.get('path')}")
            elif sha256_file(path) != digest:
                errors.append(f"paper artifact hash mismatch: {entry.get('path')}")
    return errors


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    errors = validate_paper(args.repository_root.resolve())
    if errors:
        print("paper verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("paper package valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
